Byron/trash-rs

src/macos.rs
Moves files to trash on macOS by executing an AppleScript command to
delete all requested paths.
=> feat: implementation for macOS

src/macos.rs
Updates the existing Mac implementation to compile with v2 of the
library. Does not add any new functionality other defining required
methods.
Tests fail for methods relating to `list`, `purge_all`, or
`restore_all`, which are unimplemented.
=> refactor(mac): port mac implementation to work with v2

src/lib.rs
Closes #16 
As mentioned in the issue, this would allow improved interoperability with error handling crates. I opted not to display the error code in `Display::fmt`, as I wasn't sure how the `None` case should be handled.
=> Implement std::error::Error for trash::Error

CHANGELOG.md, src/freedesktop.rs
Fixes #32
In particular when there's no home trash, the list function now returns
an empty vec instead of an error.
=> Avoid error from the list function

.github/workflows/rust.yml, Cargo.toml
Howdy! I work on [Nushell](https://github.com/nushell/nushell) and we use `trash-rs` - thanks very much for making it :)
This PR has 2 small improvements:
- Only use the `windows` crate as a build dependency on Windows.
- This dramatically speeds up building `trash-rs` on Linux; it goes from ~9s to ~4s using `cargo build --jobs 2` (the `--jobs 2` is to simulate a GitHub test runner with only 2 cores) on my machine
- Add names to the various `cargo *` CI steps, makes them easier to identify in the GitHub Actions UI
Let me know what you think; happy to break those into separate PRs if you prefer.
=> Only build `windows` on Windows, CI naming

src/lib.rs
The use case I have is that I need to restore slices from a `Vec`, which are references but but `restore_all` takes owned `TrashItem`s, so cloning is needed. I think it is better to change the api to use references but this is simpler. Having `Clone` available is also generally useful.
=> derive Clone for TrashItem

Cargo.toml, src/freedesktop.rs, src/windows.rs
Hello it's me from #51 again!
[The `windows` crate](https://github.com/microsoft/windows-rs) has seen a bit more churn recently, and I figured it might be worth proactively upgrading the version used by `trash-rs`.
Functionality-wise this should not change anything. I measured compile times before+after and it seems about 5% faster now.
=> Upgrade windows crate from v0.37 to v0.43

src/freedesktop.rs, src/lib.rs
I think formatting the file system error into `Error::Unknown` is inconvenient. It is more appropriate to separate it from `Unknown` because it has a structured body.
=> Keep detailed file system error for users using **freedesktop**

Cargo.toml, rustfmt.toml, src/freedesktop.rs, src/lib.rs, src/macos.rs, src/tests.rs, src/windows.rs, tests/trash.rs
Most recent version published on crates.io.
On github there already exists a tag for `0.45` with minor changes to `windows-sys` but not `windows`.
https://github.com/microsoft/windows-rs/releases/tag/0.45.0
According to my limited understanding this change should not affect the semver major version.
Motivated by attempt to reduce dependency duplication in [nushell](https://github.com/nushell/nushell/pull/7911/files#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87e)
=> Update `windows` crate to `0.44`

Cargo.toml, src/lib.rs, tests/isolated.rs
Previously passing "" for deletion wuold delete the current working directory
as it would canonicalize any input path without validating the path is non-empty.
=> fix: disallow empty paths from being deleted. (#73)

Cargo.toml
`chrono` crate enables `oldtime` feature by default, which has a vulnerability (https://rustsec.org/advisories/RUSTSEC-2020-0071).
=> Don't use `oldtime` feature of chrono

src/freedesktop.rs, src/lib.rs, src/tests.rs, src/windows.rs
`purge_all` implementation for https://github.com/Byron/trash-rs/issues/54 .
The reason why accepting owned items even though we can take only references is compatibility. Refer to https://github.com/Byron/trash-rs/pull/65#issuecomment-1665062549 .
---
This PR **is not fully compatible**. It would cause the scene whose type is ambiguous fails compiling, see below:
```rust
fn purge_empty() {
// error!
trash::os_limited::purge_all(vec![]).unwrap();
}
```
You need to declare the type:
```rust
fn purge_empty() {
trash::os_limited::purge_all::<Vec<trash::TrashItem>>(vec![]).unwrap();
}
```
But I believe the scenes are extremely rare in practice.
=> `purge_all` allows passing in items' ownership or reference

Cargo.toml, src/freedesktop.rs
A step closer to fix https://github.com/Byron/trash-rs/issues/83
@Byron don't know if it's feasible with a partial fix but, the remaining issue needs to be fixed in `libc` crate.
> [!WARNING]
> CI doesn't currently test that target, and it being green falsely suggests that this PR works as is.
=> NetBSD support

Cargo.toml, src/freedesktop.rs
Fixes https://github.com/Byron/trash-rs/issues/86
@Byron Probably possible to simplify but, let's wait for a confirmation in the referenced issue.
=> Restore statfs for FreeBSD & OpenBSD

Cargo.toml, src/freedesktop.rs
Found downstream via [czkawka](https://sting.dragonflybsd.org/dports/logs/sysutils___czkawka.log). This is a blind fix as I don't use DragonFly but one can set up CI via [dragonflybsd-vm](https://github.com/vmactions/dragonflybsd-vm).
DragonFly forked from FreeBSD ~20 years ago, so [getmntinfo(3)](https://man.dragonflybsd.org/?command=getmntinfo&section=3) API is the same but the implementation lacks recent changes like https://github.com/freebsd/freebsd-src/commit/5a28df2e1353 and https://github.com/freebsd/freebsd-src/commit/34ed0c63c878. DragonFly unlike FreeBSD also has [getmntvinfo(3)](https://man.dragonflybsd.org/?command=getmntvinfo&section=3) which uses `statvfs` similar to NetBSD [getmntinfo(3)](https://man.netbsd.org/getmntinfo.3) but NetBSD lacks getmntvinfo(3) (thus …
=> Unbreak build on DragonFly

.github/workflows/rust.yml, Cargo.toml
WIP PR to support cargo cross (for netbsd).  See https://github.com/Byron/trash-rs/pull/87
cc @0323pin @Byron
=> build: update ci job to use cargo-cross

src/freedesktop.rs, src/lib.rs
I think the file system (freedesktop only) error provided in the current version is too imprecise. So I make the following improvements:
- Any errors coming from `std::fs` will be returned with the path using by the `fs` function.
- Change the `std::io::ErrorKind` in `Error::FileSystem` to `std::io::Error`
I have to apologize for my immaturity; I thought `ErrorKind` is enough to be the error source so I took it in.
=> More precise file system error

Cargo.toml, examples/metadata.rs, src/freedesktop.rs, src/lib.rs, src/windows.rs
Resolves #94, adds a metadata function to get the type of the item (file or folder) and the size (in bytes for files or entries for folders). This is implemented for Freedesktop platforms and Windows
=> Add metadata function

src/freedesktop.rs
If the user has a drive mounted at `/run` and `/run/media/test`, and they are trashing a file `/run/media/test/remove-me`, depending on the order the mount point iterates through, it could incorrectly choose `/run` as the mount point, leading to a failed trash.
This simple pull request takes the longest valid mount point and uses that for the trash directory. This should prevent the issue above.
Note: I have not done too much rust development, so I'm not entirely sure that this is the simplest way to solve this. Please let me know if you see of anything that can be improved. 
Related: #57
=> Choose the longest valid mount point

src/lib.rs, src/macos.rs, src/windows.rs
Addresses #96.
Adds an `Error::Os` variant so clients can more easily handle errors.
On Windows, maps errors immediately if a file is not found or not accessible.
=> Enhanced error reporting

src/freedesktop.rs, src/lib.rs
This is a small refactor to support listing Freedesktop compliant trash bins.
Enumerating trash bins, which may reside across mount points or be invalid in some way, is useful for end users who need the paths themselves rather than the items in the trash.
=> List valid trash bin paths

Cargo.toml, src/windows.rs
This also removes a bunch of hard-coded constants, which now have bindings in the `windows` crate.
=> Bump windows crate to 0.56.0

Cargo.toml, src/macos.rs
The [`objc2`](https://github.com/madsmtm/objc2) project is the successor to `objc` and `cocoa`, and contains automatically generated bindings to the Foundation framework (and many other frameworks), while ensuring that memory management rules are upheld.
This allows `trash` to get rid of a bunch of complex `unsafe` code and error cases that can't happen (most of these are cases where the APIs are documented to not return NULL).
=> macOS: Use `objc2-foundation`

Cargo.toml, src/freedesktop.rs, src/lib.rs, src/tests.rs, src/windows.rs, tests/trash.rs
Closes: #105 
I only replaced the `unwrap()`s that directly affect the issue. I also wrote unit tests to verify the new code works.
I switched `url` to a lower level crate, `urlencoding`, because `url` only operated on Rust Strings.
Finally, and probably most concerning, I modified the public API a teensy bit. `TrashItem` 's `name` field is an `OsString` now instead of a `String`. Beyond that, I didn't modify any public APIs.
=> fix: Support non-Unicode paths

src/freedesktop.rs
Fixes #112 
Not sure if this is the best/proper way to fix this, but it works on my system:
=> Fix trashing files on Fedora Atomic variants

src/freedesktop.rs, src/lib.rs, src/tests.rs, src/windows.rs
`is_empty()` is a short circuiting function that checks if the trash is empty on Freedesktop compatible systems and Windows.
The main purpose of `is_empty()` is to avoid evaluating the entire trash context when the caller is only interested in whether the trash is empty or not. This is especially useful for full trashes with many items.
I have to write unit tests, so I'll keep this as a draft till tomorrow or so.
=> feat: Short circuiting check for empty trash

README.md, examples/delete_method.rs, examples/hello.rs, src/freedesktop.rs, src/lib.rs, src/macos.rs, src/tests.rs, tests/trash.rs
`create` has a tiny chance of deleting existing files, so just in case replaced with `create_new`, which fails in this case 
> and will truncate it if it does
not sure what how tests re. lifetimes are related to these changes
=> Fail in tests on truncating pre-existing user files

src/macos.rs
There are 2 ways to trash files: via the ≝Finder app or via the OS NsFileManager call
| <br>Feature	|≝<br>Finder	|<br>NsFileManager	|
|:--------|:-----:|:-----------:|
|Undo via "Put back" 	| ✓          	| ✗          	|
|Speed               	| ✗<br>Slower	| ✓<br>Faster	|
|No sound            	| ✗          	| ✓          	|
|No extra permissions	| ✗          	| ✓          	|
=> doc: add an overview table to DeleteMethod on Mac

Cargo.toml, src/macos.rs, tests/trash.rs
Adds a utf8 conversion step to allow creating valid Mac URLs for its file manager APIs as well as Finder
- via a fast simd method if everything is fine
- on fail replaces bytes in invalid utf8 sequences with %-encoded utf8 strings that are valid paths
fixes: https://github.com/Byron/trash-rs/issues/124
Test: the actual delete tests are **DISABLED** since they fails in CI and locally by default since modern APFS doesn't allow binary paths, but I've manually tested on a HFS usb drive that supports it.
Is there an easy way to create some virtual FS during testing so that the test works both locally and in CIs and doesn't require manual intervention?
Also for some reason got the same non-Mac unrelated clippy errors
=> Add support for binary paths on macOS

src/macos.rs
Closes https://github.com/Byron/trash-rs/issues/130
=> mac: Escape quoted paths in AppleScript

Cargo.toml
The next version of the `objc2` framework crates will have a bunch of default features enabled, see https://github.com/madsmtm/objc2/issues/627, so this PR pre-emptively disables them, so that your compile times down blow up once you upgrade to the next version (which is yet to be released, but will be soon).
=> Prepare for `objc2` frameworks v0.3

src/freedesktop.rs
Fixes the value of S_ISVTX to use octal `0o1000` instead of hexadecimal `0x1000` (= `0o10000`) in `folder_validity`.
I found this because I was unable to trash files in some mounted drives. This change fixes the issue.
This is some pretty old code and I'm a little surprised nobody noticed until now, so let me know if I'm missing something here. This doesn't affect "home" trash directories as they aren't validated by this, which may explain some of it, but does affect trash directories in other mount points.
=> Use octal for S_ISVTX sticky bit check

Cargo.toml, src/macos/mod.rs
Hello there! Thanks for this crate.
Please review this very tiny change: upgrading the objc2 version.
The old version breaks compatibility with some other crates.
=> mac: upgrade objc2
